name: 'dbt_artifacts'
version: '0.1.0'
config-version: 2
require-dbt-version: ">=0.19.0"

models:
  dbt_artifacts:
    +schema: default_dbt_artifacts_schema
    +materialized: table
    incremental:
      +materialized: incremental
    staging:
      +materialized: view # The staging tables cannot be ephemeral
