name: "dbt_artifacts"
version: "2.9.2"
config-version: 2
require-dbt-version: [">=1.3.0", "<1.10.0"]
profile: "dbt_artifacts"

clean-targets: # folders to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_artifacts:
    +materialized: view
    +file_format: delta
    sources:
      +materialized: incremental
      +full_refresh: false
      +persist_docs:
        # Databricks and SQL Server don't offer column-level support for persisting docs
        columns: '{{ target.name != "databricks" and target.type != "sqlserver" }}'
        relation: '{{ target.type != "sqlserver" }}'
      +as_columnstore: False
