version: 2

sources:
  - name: dummy_source
    database: "{% if target.type not in ('spark', 'databricks') %}{{ var('dbt_artifacts_database', target.database) }}{% endif %}"
    schema: "{{ target.schema }}"
    tables:
      - name: doesnt_exist
      - name: '"GROUP"'

  - name: freshness_check
    database: "{% if target.type not in ('spark', 'databricks') %}{{ var('dbt_artifacts_database', target.database) }}{% endif %}"
    schema: "{{ target.schema }}"
    freshness:
      error_after: {count: 3, period: day}
      warn_after: {count: 1, period: day}
    loaded_at_field: load_timestamp
    tables:
      - name: freshness
