name: 'artifacts_integration_tests'
version: '1.0'
config-version: 2

profile: 'dbt_artifacts'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  test_dbt_vars_1: dbt_vars_1
  test_dbt_vars_2: dbt_vars_2
  test_dbt_vars_3: dbt_vars_3
  env_vars: [
    'TEST_ENV_VAR_1'
  ]
  dbt_vars: [
    'test_dbt_vars_1',
    'test_dbt_vars_2',
    'test_dbt_vars_3'
  ]


models:
  +persist_docs:
    relation: true
    columns: true
seeds:
  +quote_columns: false

on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"
