name: "artifacts_integration_tests"
version: "1.0"
config-version: 2

profile: "dbt_artifacts"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

vars:
  test_dbt_vars_1: dbt_vars_1
  test_dbt_vars_2: dbt_vars_2
  test_dbt_vars_3: dbt_vars_3
  env_vars:
    ["TEST_ENV_VAR_NUMBER", "TEST_ENV_VAR_EMPTY", "TEST_ENV_VAR_WITH_QUOTE"]
  dbt_vars: ["test_dbt_vars_1", "test_dbt_vars_2", "test_dbt_vars_3"]
  dbt_artifacts_exclude_all_results: true

models:
  +persist_docs:
    relation: '{{ target.name != "sqlserver" }}' # sqlserver-adapter doesn't support this
    columns: '{{ target.name != "sqlserver" }}' # sqlserver-adapter doesn't support this
seeds:
  +quote_columns: false

flags:
  source_freshness_run_project_hooks: true
  send_anonymous_usage_stats: false
  use_colors: true

on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"
