name: 'artifacts_integration_tests'
version: '1.0'
config-version: 2

profile: 'dbt_artifacts_integration_tests'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_modules"]

quoting:
  identifier: false
  schema: false

seeds:
  +quote_columns: false
